<script setup>
    import { ref, onMounted } from 'vue'

    const images = ref([])
    const previewImage = ref(null)

    onMounted(() => {
        // Generated by AI
        const globImages = import.meta.glob('../assets/gallery/*.webp', { eager: true })
        images.value = Object.values(globImages).map(img => ({
            src: img.default,
            alt: img.default.split('/').pop().replace(/\.[^.]+$/, '').replace(/_/g, ' ')
        }))
    })
</script>

<template>
    <body>
        <img class="banner" src="../assets/osao_kotkantie1.webp">
        <h1>Galleria</h1>
        <hr style="width: 80vw;">
        <div class="main-gallery">
            <img class="preview" @click="previewImage = image" v-for="image in images" :src="image.src" :alt="image.alt">
        </div>
        <img class="big-preview" @click="previewImage = null" v-if="previewImage" :src="previewImage.src" :alt="previewImage.alt">
    </body>
</template>

<style scoped src="../assets/styles/FlexBody.css"></style>
<style scoped>
    body {
        margin-bottom: 50px;
        justify-content: initial;
    }

    h1 {
        text-align: center;
        margin-bottom: 20px;
        margin-top: 20px;
    }

    .banner {
        width: 100vw;
        mask-image: linear-gradient(to bottom, black 60%, transparent 100%);
        -webkit-mask-image: linear-gradient(to bottom, black 60%, transparent 100%);
    }

    .gallery {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .main-gallery {
        display: grid;
        justify-content: center;
        width: 100vw;
        grid-template-columns: repeat(auto-fit, minmax(200px, 200px));
        gap: 10px;
        overflow: visible;
        padding-left: 5vw;
        padding-right: 5vw;
    }

    .preview {
        width: 200px;
        height: 200px;
        object-fit: cover;
        border-radius: 20px;
        padding: 5px;
        transition: scale 0.1s ease-in-out;
    }

    .preview:hover {
        scale: 0.95;
    }

    .preview:active {
        scale: 0.9;
    }

    .big-preview {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 80vw;
        height: 80vh;
        object-fit: contain;
        z-index: 9999;
        background-color: black;
        border-radius: 20px;
    }
</style>
