<template>
    <main>
        <div class="description">
            <h1>Kotkantien maalaus- ja tapetointi</h1>
            <h2>Kotimaista suunnittelua</h2>
            <hr>
            <!--Two lines below were generated by AI-->
            <p>Teemme kodistasi kodin – laadukasta maalausta ja tapetointia, joka kestää aikaa.</p>
            <p>Kotkantien maalaus- ja tapetointi on perinteikäs suomalainen yritys, joka on palvellut asiakkaitaan jo vuosikymmenien ajan. Tarjoamme ammattimaista apua sekä pienempiin kodin päivityksiin että suurempiin uudisrakennuskohteisiin. Laatu, luotettavuus ja asiakastyymytys ovat meille paras mainos.</p>
            <hr>
            <p>Testaa meidän suunnittelu työkaluita!</p>
            <div>
                <a class="btn btn-primary" @click="$router.push('/studio/wall')">Seinien Suunnittelu Studio</a>
                <a class="btn btn-primary" @click="$router.push('/studio/palette')">Paletti Rakentaja</a>
            </div>
        </div>
        <div class="image">
            <img src="../assets/home-unsplash.jpg" alt="">
        </div>
    </main>
</template>

<style scoped src="../assets/styles/FlexBody.css"></style>
<style scoped>
    main {
        flex-direction: initial;
        gap: 3vw;
        padding: 5%;
    }

    img {
        height: clamp(150px, 45vw, 85vh);
        border-radius: 20px;
        margin-top: -75px;
    }

    p {
        font-size: large;
        font-weight: 450;
    }

    .description {
        margin-top: -75px;
        gap: 15px;
    }

    .description h1, h2 {
        text-align: left;
    }

    .btn {
        color: white;
        margin-right: 8px;
        border-radius: 15px;
    }

    @media (max-width: 1000px) {
        .image {
            display: none;
        }

        .description,
        .description h1,
        h2 {
            text-align: center;
        }
    }
</style>
