<script setup>
    import { ref, computed } from 'vue';
    import Form from '../components/Form.vue';
    import paintingImg from '../assets/gallery/pexels-pavel-danilyuk-6764282.webp'
    import wallpaperImg from '../assets/gallery/pexels-artbovich-7546769.webp'

    const selectedService = ref('');
    const showForm = ref(false);

    const services = computed(() => [
        {
            name: 'Maalaus',
            image: paintingImg,
            // Generated by AI
            description: 'Ammattimaista sisä- ja ulkomaalausta, joka tuo kodillesi uuden värin ja suojaa pintoja vuosiksi.'
        },
        {
            name: 'Tapetointi',
            image: wallpaperImg,
            // Generated by AI
            description: 'Laadukasta tapetointia kodeihin ja tiloihin, joka lisää kodillesi ilmettä ja mukavuutta.'
        }
    ]);

    const openService = service => {
        selectedService.value = service;
        showForm.value = true;
    };

    const closeForm = () => {
        showForm.value = false;
        selectedService.value = '';
    };
</script>

<template>
    <main class="services-page">
        <div v-for="service in services" :key="service.name" class="service-card">
            <div class="service-card-image">
                <img :src="service.image" :alt="service.name" />
            </div>
            <div class="service-card-body">
                <h2 class="service-card-title">{{ service.name }}</h2>
                <p class="service-card-description">{{ service.description }}</p>
                <button class="btn btn-primary service-card-btn" @click="openService(service.name)">Osta</button>
            </div>
        </div>

        <Teleport to="body">
            <div v-if="showForm" class="form-overlay" @click.self="closeForm" @touchmove.stop>
                <Form :service="selectedService" @close="closeForm" />
            </div>
        </Teleport>
    </main>
</template>

<style scoped src="../assets/styles/FlexBody.css"></style>
<style scoped>
    main {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        justify-items: center;
        gap: 16px;
        max-width: 900px;
        margin: 40px auto;
        padding: 20px;
    }

    .service-card {
        background-color: #fff;
        border-radius: 16px;
        overflow: hidden;
        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
        display: flex;
        flex-direction: column;
        max-width: 300px;
        height: 500px;
    }

    .service-card-image {
        height: 180px;
        overflow: hidden;
    }

    .service-card-image img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        display: block;
    }

    .service-card-body {
        padding: 20px;
        display: flex;
        flex-direction: column;
        gap: 14px;
        flex: 1;
    }

    .service-card-title {
        margin: 0;
        font-size: 1.25rem;
        color: #1a1a1a;
    }

    .service-card-description {
        margin: 0;
        color: #666;
        line-height: 1.5;
        font-size: 0.95rem;
        flex: 1;
    }

    .service-card-btn {
        margin-top: auto;
        width: 100%;
        min-height: 44px;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #1a1a1a;
        color: #fff;
        border: none;
        border-radius: 8px;
        font-size: 16px;
        cursor: pointer;
    }

    .form-overlay {
        position: fixed;
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1000;
        padding: 16px;
    }

    .form-overlay :deep(.form-container) {
        background: white;
        padding: 24px;
        border-radius: 16px;
        max-width: 460px;
        width: 100%;
        max-height: 85dvh;
        overflow-y: auto;
    }

    @media (max-width: 480px) {
        main {
            grid-template-columns: 1fr;
            margin: 24px auto;
        }

        .form-overlay {
            padding: 0;
            align-items: flex-end;
        }

        .form-overlay :deep(.form-container) {
            border-radius: 16px 16px 0 0;
            max-height: 90dvh;
        }
    }
</style>
