<script setup>
    import { ref } from 'vue';
    import Form from '../components/Form.vue';
    const selectedService = ref('')
    const showForm = ref(false)
</script>

<template>
    <main class="services-page">
        <div class="service-card">
            <img src="../assets/gallery/pexels-pavel-danilyuk-6764282.webp" alt="Maalaus">
            <h2>Maalaus</h2>
            <!-- Generated by AI -->
            <p>Maalausta</p>
            <a class="btn btn-primary" @click="selectedService = 'Maalaus'; showForm = true">Osta</a>
        </div>
        <div class="service-card">
            <img src="../assets/gallery/pexels-artbovich-7546769.webp" alt="Tapetointi">
            <h2>Tapetointi</h2>
            <!-- Generated by AI -->
            <p>Tapetointia</p>
            <a class="btn btn-primary" @click="selectedService = 'Tapetointi'; showForm = true">Osta</a>
        </div>
        <Teleport to="body">
            <div v-if="showForm" class="form-overlay" @click.self="showForm = false" @touchmove.stop>
                <Form :service="selectedService" @close="showForm = false; selectedService = ''" />
            </div>
        </Teleport>
    </main>
</template>

<style scoped>
    main {
        display: grid;
        gap: 15px;
        grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        padding: 15px;
        min-height: 100vh;
    }

    .service-card {
        background-color: gray;
        padding: 15px;
        display: flex;
        flex-direction: column;
        align-items: center;
        border-radius: 30px;
        color: white;
        gap: 15px;
        width: 100%;
    }

    .service-card img {
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-radius: 15px;
    }

    .service-card .btn {
        width: 100%;
        min-height: 44px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .form-overlay {
        position: fixed;
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1000;
        padding: 16px;
    }

    .form-overlay :deep(.form-container) {
        background: white;
        padding: 24px 20px;
        border-radius: 15px;
        max-width: 500px;
        width: 100%;
        max-height: 85dvh;
        overflow-y: auto;
    }

    @media (max-width: 480px) {
        .services-page {
            grid-template-columns: 1fr;
            padding: 12px;
            gap: 12px;
        }

        .form-overlay {
            padding: 0;
            align-items: flex-end;
        }

        .form-overlay :deep(.form-container) {
            border-radius: 15px 15px 0 0;
            max-height: 90dvh;
            padding: 20px 16px;
        }
    }
</style>
